require('core.plugin_config.colors')
require('core.plugin_config.lualine')
require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.lsp')
require('core.plugin_config.completion')
